# Generated by Django 2.2 on 2022-11-21 13:36

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20221121_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/product/2022-11-21 13:36:28.505230/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[product.models.rating_validation]),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='image',
            field=models.ImageField(upload_to='images/product/2022-11-21 13:36:28.505230/'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[product.models.rating_validation]),
        ),
    ]
