# Generated by Django 2.2 on 2022-11-22 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20221122_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('cart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Cart')),
                ('amount', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('product.cart',),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/product/2022-11-22 16:48:42.914458/'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='image',
            field=models.ImageField(upload_to='images/product/2022-11-22 16:48:42.914458/'),
        ),
    ]
