# Generated by Django 2.2 on 2022-11-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20221122_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_receive_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/product/2022-11-22 18:48:12.923888/'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='image',
            field=models.ImageField(upload_to='images/product/2022-11-22 18:48:12.923888/'),
        ),
    ]
