# Generated by Django 2.2 on 2022-11-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20221123_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(upload_to='images/user/2022-11-24 18:01:33.623551/'),
        ),
    ]
